### ISSUE TITLE
mvn clean install fails from an initial clean clone

### ISSUE THREAD

**Issue by mooreb** [GreenButtonAlliance/OpenESPI-Common-java#310]
As of the commits below, i am unable to mvn clean install per the attached typescript.

commit b2bb0978ea3475390d8af8e4ddf926b66df0eb68
Author: Donald F Coffin <donald.coffin@reminetworks.com>
Date:   Tue Feb 12 13:32:25 2019 -0500

    1) Add org.junit.Assert.assertEquals import

commit 3c472829765d9530530b0df1e9ad4df805ae10d3
Author: Donald F Coffin <donald.coffin@reminetworks.com>
Date:   Tue Feb 12 13:24:35 2019 -0500

    1) Add javax.xml.bind dependencies

commit a664404c4406e984a7c89555503b1aeb2cb17703
Author: DonaldCREMI <donald.coffin@reminetworks.com>
Date:   Tue Feb 12 12:25:52 2019 -0500

    Update Copyright notice

commit 57fc1ea05e58fc902ae244221f3d695b3e3d55b3
Merge: 10fded3 d88bd4d
Author: DonaldCREMI <donald.coffin@reminetworks.com>
Date:   Tue Feb 12 12:22:32 2019 -0500

    Sychronize with GitHub repository

commit 10fded37e646f14b65811def0237b8076c706bea
Author: DonaldCREMI <donald.coffin@reminetworks.com>
Date:   Tue Feb 12 11:31:05 2019 -0500

    Synchronize descriptions with ESPI UML Model changes

Please find typescript below:

[typescript.txt](https://github.com/GreenButtonAlliance/OpenESPI-Common-java/files/2871688/typescript.txt)

**Comment by dfcoffin** [comment]
@mooreb Please use the following maven command to build the Common.jar file:

`mvn -P <profile name> -Dmaven.test.skip=true clean install`

The JUnit test have not been maintained since the original creation of the repository.  The errors you encountered are due to not including the "-Dmaven.test.skip=true" portion of the command shown above.
